version: "0.2"
words:
  - AZAZ
  - camelcase
  - elmerbulthuis
  - endregion
  - esbenp
  - goodrouter
  - openapi
  - Promisable
  - urlencoding
  - welkom
useGitignore: true
files: ["**"]
ignorePaths: ["specifications/"]
enableFiletypes: ["*"]
