on:
  push:
    tags:
      - ts/oa42-lib@*.*.*

jobs:
  publish:
    uses: ./.github/workflows/publish-ts.yaml
    with:
      NPM_CONFIG_WORKSPACE: oa42-lib
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
