on:
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - packages-ts/oa42-lib/**

jobs:
  test:
    uses: ./.github/workflows/tes-ts.yaml
    with:
      NPM_CONFIG_WORKSPACE: oa42-lib
